import asyncio
import json
import os
import threading
from contextlib import asynccontextmanager
from pathlib import Path

import faiss
import numpy as np
import uvicorn
from dotenv import load_dotenv
from mcp import types
from mcp.server import Server
from mcp.server.streamable_http_manager import StreamableHTTPSessionManager
from sentence_transformers import SentenceTransformer
from src.middleware.api_key import APIKeyMiddleware
from starlette.applications import Starlette
from starlette.middleware import Middleware
from starlette.middleware.cors import CORSMiddleware
from starlette.routing import Mount

load_dotenv()

INDEX_PATH = Path(os.environ.get("INDEX_PATH", "./faiss_index")).resolve()
TOP_K = int(os.environ.get("TOP_K", 8))
EMBED_MODEL = os.environ.get("EMBED_MODEL", "all-MiniLM-L6-v2")


class VectorStore:
    """Thread-safe search engine utilizing pre-computed FAISS indexes and JSON metadata."""

    def __init__(self, embed_model: str, index_path: Path) -> None:
        self._model = SentenceTransformer(embed_model)
        self._chunks: list[dict] = []
        self._indexed_files: set[str] = set()
        self._index: faiss.IndexFlatIP = None
        self._lock = threading.Lock()
        self._index_path = index_path

    def load(self) -> bool:
        """Loads the pre-built FAISS index and JSON chunks mapping generated by CI/CD."""
        idx_file = self._index_path / "index.faiss"
        meta_file = self._index_path / "chunks.json"

        if not idx_file.exists() or not meta_file.exists():
            print(f"Error: Pre-built index files missing at {self._index_path}")
            return False

        with self._lock:
            self._index = faiss.read_index(str(idx_file))

            with open(meta_file, "r", encoding="utf-8") as f:
                data = json.load(f)
            self._chunks = data["chunks"]
            self._indexed_files = set(data["indexed_files"])

        print(
            f"Ready: Loaded {len(self._chunks)} chunks across {len(self._indexed_files)} indexed files."
        )
        return True

    def list_pdfs(self) -> list[str]:
        with self._lock:
            return sorted(list(self._indexed_files))

    def search(
        self,
        query: str,
        top_k: int = TOP_K,
        filename_filter: str | None = None,
    ) -> list[tuple[float, dict]]:
        with self._lock:
            total = len(self._chunks)
            if total == 0 or self._index is None:
                return []
            chunks_snapshot = self._chunks

        query_vec = self._model.encode([query], normalize_embeddings=True)
        query_vec = np.array(query_vec, dtype="float32")

        fetch_k = min(top_k * 10 if filename_filter else top_k, total)

        with self._lock:
            scores, indices = self._index.search(query_vec, fetch_k)

        results: list[tuple[float, dict]] = []
        seen: set[tuple[str, int]] = set()

        for score, idx in zip(scores[0], indices[0]):
            if idx < 0:
                continue
            meta = chunks_snapshot[idx]
            key = (meta["filename"], meta["chunk"])
            if key in seen:
                continue
            if filename_filter and meta["filename"] != filename_filter:
                continue
            seen.add(key)
            results.append((float(score), meta))
            if len(results) == top_k:
                break

        return results


_store = VectorStore(EMBED_MODEL, INDEX_PATH)
server = Server("Akten für das Bundesarchiv")


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(
            name="list_pdfs",
            description="List all available indexed files.",
            inputSchema={"type": "object", "properties": {}},
        ),
        types.Tool(
            name="search",
            description=(
                "Semantic search across all contexts. Returns the most relevant passages "
                "for a natural-language query. Optionally filter to a single file."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "query": {"type": "string"},
                    "filename": {
                        "type": "string",
                        "description": "Optional: restrict search to this resource target.",
                    },
                    "top_k": {
                        "type": "integer",
                        "description": f"Number of results to return (default {TOP_K}).",
                    },
                },
                "required": ["query"],
            },
        ),
    ]


@server.call_tool()
async def call_tool(name: str, arguments: dict) -> list[types.TextContent]:
    def _err(msg: str) -> list[types.TextContent]:
        return [types.TextContent(type="text", text=f"Error: {msg}")]

    try:
        if name == "list_pdfs":
            pdfs = _store.list_pdfs()
            text = "\n".join(pdfs) if pdfs else "(no source metadata available)"
            return [types.TextContent(type="text", text=text)]

        elif name == "search":
            query = arguments.get("query", "").strip()
            if not query:
                return _err("'query' parameter requirement missing.")

            top_k = int(arguments.get("top_k", TOP_K))
            filename_filter = arguments.get("filename")

            results = _store.search(query, top_k=top_k, filename_filter=filename_filter)

            if not results:
                return [
                    types.TextContent(type="text", text="No semantic records matched.")
                ]

            lines = [
                f"[{m['filename']} | chunk {m['chunk']} | match confidence {s:.3f}]\n{m['text']}"
                for s, m in results
            ]
            return [types.TextContent(type="text", text="\n\n---\n\n".join(lines))]

        return _err(f"Action command context unknown: {name!r}")

    except Exception as exc:
        return _err(f"Unexpected error executing tool '{name}': {exc}")


session_manager = StreamableHTTPSessionManager(
    app=server,
    event_store=None,
    json_response=True,
    stateless=True,
)


@asynccontextmanager
async def lifespan(_app):
    await asyncio.get_event_loop().run_in_executor(None, _store.load)
    async with session_manager.run():
        yield


async def handle_mcp(scope, receive, send):
    await session_manager.handle_request(scope, receive, send)


app = Starlette(
    middleware=[
        Middleware(
            CORSMiddleware,
            allow_origins=["*"],
            allow_methods=["*"],
            allow_headers=["*"],
        ),
        Middleware(APIKeyMiddleware),
    ],
    routes=[Mount("/", app=handle_mcp)],
    lifespan=lifespan,
)

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
